### ISSUE TITLE
当cat没有被初始化（启用）的时候，DubboCatCrossFilter的179行回报转型错误

### ISSUE THREAD

**Issue by lewis600** [joonk2016/cat-monitor#1]
private void completeEvent(Event event){
        AbstractMessage message = (AbstractMessage) event;
        message.setCompleted(true);
}
Event有可能是一个NullMessage，所以转型就报错了，增加一个判断就好了，来兼容cat禁用的时候
 if (event != NullMessage.EVENT) {
            AbstractMessage message = (AbstractMessage) event;
            message.setCompleted(true);
 }

**Comment by summerpotato** [comment]
还没有遇到过这种情况，学习了，已改，多谢 :p
